USE Superstore;

-- ============================================
-- QUERY: Profitability by Category and Sub-Category
-- PURPOSE: Identify which product lines make or lose money
-- ============================================

SELECT 
    -- Product classification
    Category, 
    Sub_Category,
    
    -- Count of individual line items (orders) in this category/sub-category
    COUNT(*) AS num_orders,
    
    -- Total revenue generated by this category/sub-category
    SUM(Sales) AS total_sales,
    
    -- Total profit (or loss) generated by this category/sub-category
    SUM(Profit) AS total_profit,
    
    -- Overall profit margin as a percentage
    -- Formula: Total Profit / Total Sales * 100
    -- This gives the true margin, not an average of row-level margins
    (SUM(Profit) / SUM(Sales)) * 100 AS margin_Perc

FROM superstore

-- Group results by both Category and Sub-Category to see granular performance
GROUP BY Category, Sub_Category

-- Sort from highest margin to lowest margin
-- Positive = profitable, Negative = losing money
ORDER BY margin_Perc DESC;