USE Superstore;

-- ============================================
-- QUERY: Top Customer Analysis
-- PURPOSE: Identify the most profitable customers and their segments
-- KEY QUESTION: Who are our best customers and what do they look like?
-- ============================================

SELECT TOP 20
    -- Unique customer identifier
    Customer_ID,
    
    -- Customer full name
    Customer_Name,
    
    -- Customer segment: Consumer, Corporate, or Home Office
    Segment,
    
    -- Count of unique orders placed by this customer
    -- DISTINCT needed because one order can have multiple line items
    COUNT(DISTINCT Order_ID) AS Total_Orders,
    
    -- Total revenue generated by this customer across all orders
    SUM(Sales) AS Total_Sales,
    
    -- Total profit generated by this customer across all orders
    SUM(Profit) AS Total_Profit,
    
    -- Overall profit margin for this customer
    -- Formula: Total Profit / Total Sales
    -- Shows how efficiently this customer generates profit
    SUM(Profit) / SUM(Sales) AS Avg_Margin

FROM superstore

-- Group all transactions by customer to summarize each one
GROUP BY Customer_ID, Customer_Name, Segment

-- Sort by total profit descending to show best customers first
ORDER BY Total_Profit DESC;